### ISSUE TITLE
Refactoring [tracker/issue]

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#255]
Work will done in this branch: [refactor](https://github.com/NeoVintageous/NeoVintageous/tree/refactor) .

[![Build Status](https://travis-ci.org/NeoVintageous/NeoVintageous.svg?branch=refactor)](https://travis-ci.org/NeoVintageous/NeoVintageous) [![Build status](https://ci.appveyor.com/api/projects/status/g4pkv4ws1k2r1xna/branch/refactor?svg=true)](https://ci.appveyor.com/project/gerardroche/neovintageous/branch/refactor)

 * [x] Push all `.py` into `lib` folder except one, `nvim.py`, which will be responsible for initialising anything that need to be initialised and load all the ST commands. `nvim.py` will be a sort of kernel for the plugin.
   - [x] jumplist
   - [x] modelines
   - [x] ex 
     - [x] motions
     - [x] commands
     - [x] main
   - [x] extras
     - [x] surround 
   - [x] actions
   - [x] motions
   - [x] support
   - [x] events
* [x] Push all resources that don't need to be loaded on start into `res` folder
* [x] Logging
  - [x] Replace with something smaller and simpler.
  - [x] Disable logger by default
* [ ] Renaming things from "vintageous" to "neovintageous" or to generic terms
  - [ ] Rename `.vintageousrc` to `.neovintageousrc`
  - [ ] Rename all settings from `vintageous_` to `neovintageous.`
  - [ ] Rename internal settings e.g. `VintageousEx_linux_terminal` to `NeoVintageousEx_linux_terminal`, `_vintageous_last_buffer_search` to `_neovintageous_last_buffer_search`
  - [x] Rename files e.g. `VintageousEx Cmdline.tmLanguage` to `NeoVintageousEx Cmdline.tmLanguage` or a generic name e.g. `Ex Cmdline.tmLanguage`
  - [x] Rename commands, functions, etc. e.g. function `_init_vintageous` to `_init_neovintageous` or something more generic
  - [ ] Auto copy/migrate any of the user's vintageous settings to neovintageous
  - [x] Rename `output.vintageous.tests` to `output.neovintageous.tests`
* [ ] Replace all `print("NeoVintageous...` with a function that doesn't need the name of the package`
* [ ] Refactor status messages. Replace all `...status_message("NeoVintageous...` with a

**Comment by trishume** [comment]
This all looks good, I think I agree with everything except renaming the settings, I think we should keep it so that users config files continue to work.

It's probably a good idea to name any new settings we add `neovintageous` though, like the one for surrounding that I added already.

**Comment by gerardroche** [comment]
It would be nice if we can migrate the settings in some future major version. For the moment it's not that important. When we do eventually migrate the settings it can be done transparently meaning the user's existing settings will be copied across to the new settings so their settings won't suddenly change. Most user's wouldn't even notice.

**Comment by gerardroche** [comment]
Ok. I think that's refactoring in this cycle. I'd like to get these changes released in 1.1.0, so I've merged the current refactorings into the develop branch. Technically, in terms of semver, these changes require major version bump, but let's not be too strict about semver. Most of the breaking changes are internal or would on;y affect neovintageous plugins and neovintageous isn't even in the package control channel yet so it won't break much at all.

There are several important loading and reloading fixes so it will be good to get these released.

@trishume What branch do you actively use and on what OS do you regularly work? Can you test the current develop and let me know if it's good to be released.

For anybody interested in helping test NeoVintageous please checkout the develop branch and let us know if you have any problems. Be sure to let us know what OS and sublime version you are working with too. Thanks.

**Comment by trishume** [comment]
I'm using OSX with the latest ST3 dev build and I just tested the develop branch for a bit and it seems to work fine, including the surround plugin.
