### ISSUE TITLE
Refactoring [tracker/issue] Round 2

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#264]
Round 1 can be found here: #255. Incomplete tasks from Round 1 are ported over to this issue.

Work is done in the branch named [develop](https://github.com/NeoVintageous/NeoVintageous/tree/develop). 

[![Build Status](https://travis-ci.org/NeoVintageous/NeoVintageous.svg?branch=develop)](https://travis-ci.org/NeoVintageous/NeoVintageous) [![Build status](https://ci.appveyor.com/api/projects/status/g4pkv4ws1k2r1xna/branch/develop?svg=true)](https://ci.appveyor.com/project/gerardroche/neovintageous/branch/develop) [![Coverage Status](https://coveralls.io/repos/github/NeoVintageous/NeoVintageous/badge.svg?branch=develop)](https://coveralls.io/github/NeoVintageous/NeoVintageous?branch=develop)

* [x] Refactor general plugin api's into a module named `lib/nvim.py`

  My original intention was to have package root module named `nvim.py`, but library modules can't easily import that module without unwanted side effects so I ended up renaming the root module "plugin.py". That module initialises the plugin. 

  `lib/nvim.py` will contain general api's and can easily be imported by other modules.

   Some example api's:

      nvim.status_message()
      nvim.console_message()
      raise nvim.Error()

  - [x] Replace all `print("NeoVintageous...")` with `nvim.console_message()`
  - [x] Replace all `sublime.status_messages("NeoVintageous...")` with `nvim.status_message()`

  I also want to refactor some, maybe all, constants into the nvim module e.g. error constants prefixed with `E_`. Yes, the nvim module could get big with a lot of constants, but they *are* just constants. Currently the constants are littered throughout the codebase. I think it will be easier to maintain and understand the plugin if they are grouped together. I certainly want to move away from class based constants e.g. the mode constants are in `lib/vi/utils.py` in a class named modes. They would be better refactored either into a module named modes or grouped together will all other constants. 

* [x] Make testing easier

  Testing should be a easy as possible. The lower the friction the better. I'm thinking along the lines of functional testing with an api that looks something like:
  
      def test_b_in_normal_mode(self):
          self.insert('Guide to the Galaxy')
          self.select(17)
          self.feed('b', mode=self.NORMAL_MODE)
          self.assertSelection(13)

      def test_b_visual_mode(self):
          self.insert('Guide to the Galaxy')
          self.select((7, 17))
          self.feed('b', mode=self.VISUAL_MODE)
          self.assertSelection((7, 14))

      def test_cc(self):
          self.prepare('aaa\nbb|b\nccc')
          self.feed('cc')
          self.assertPrepared('aaa\n|\nccc')

  Our demographic is technical so there isn't much value in abstracting beyond python.  

Tasks put on hold

* [ ] Renaming things from "vintageous" to "neovintageous" or to generic terms
  - [ ] Rename `.vintageousrc` to `.neovintageousrc`
  - [ ] Rename all settings from `vintageous_` to `neovintageous.`
  - [ ] Rename internal settings e.g. `VintageousEx_linux_terminal` to `NeoVintageousEx_linux_terminal`, `_vintageous_last_buffer_search` to `_neovintageous_last_buffer_search`
  - [ ] Auto copy/migrate any of the user's vintageous settings to neovintageous

**Comment by gerardroche** [comment]
I removed the wip branch. Use the develop branch instead.
