### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#404]
**See the roadmap, part 2 #711** (the remaining issues have been consolidated there).

*Many items have already been backported to the current release. Where an implementation has been backported it is noted in the item.*

## Defaults

Defaults should more closely match the Neovim defaults: [part 1](https://github.com/neovim/neovim/issues/2676) and [part 2](https://github.com/neovim/neovim/issues/6289).

* [x] Enable CTRL keys by default **next major version ([2.0](https://github.com/NeoVintageous/NeoVintageous/milestone/19))**
* [x] Enable SUPER keys by default **next major version ([2.0](https://github.com/NeoVintageous/NeoVintageous/milestone/19))**
* [x] Enable ALT keys by default #579 **(Implemented as of 1.17.0)**
* [x] ~~Enable system clipboard by default?~~
* [x] Change default bell style to "view" #502 **(Implemented as of 1.12.0)**
* [x] Implement configurable default Insert mode #277 **(Implemented as of 1.15.0)**
* [x] Change default option `ignorecase` to `False` **(Implemented as of 1.19.0)** 1865e11
* [x] Change default option `winaltkeys` to `menu` **(Implemented as of 1.19.0)** d9080d5
* [x] Disable `vintageous_multi_cursor_exit_from_visual_mode` **(Implemented as of 1.18.0)**

## Settings

* [x] Rename `.vintageousrc` file to `.neovintageousrc` ~~or `.nvrc`~~ (a backwards compatibility fix is implemented that automatically renames .vintageousrc to .neovintageous). **(Backported as of 1.11.0)**
* [ ] All public settings should be prefixed with `nv_` ~`neovintageous_`~ 
* [x] All private settings should be prefixed with `_nv_`
* [x] All Vim related settings should be configurable via the `.neovintgeousrc` file instead of via Sublime settings e.g. `set hlsearch`, `set nohlsearch`, etc. #585
* [ ] All plugins should be enabled or disabled via the boolean setting `nv_{plugin_name}`
* [ ] All plugins should group related settings via the prefix `nv_{plugin_name}_`.
* [ ] Granular key control #470 #579 
* [x] Remove unused `is_vintageous_widget` setting (**Removed as of 1.18.0**)
* [x] Remove setting `__vi_external_disable_keys` (**Removed as of 1.18.0**)
       Use `__vi_external_disable` instead. This setting wasn't working as intended and pretty much does nothing does nothing more than the `__vi_external_disable` setting i.e. it disables NeoVintageous. This is useful for plugins that want to inhibit NeoVintageous on a view by view basis.
* [x] Remove settings prefixed `VintageousEx` dc41a3c
* [x] Remove setting `linux_shell` dc41a3c

## Command and mapping keys completeness

* [x] Add `<C-space>`  **(Implemented as of 1.19.0)**
* [x] Add `<insert>` alias to `i`  **(Implemented as of 1.19.0)**
* [x] Add `<Del>`
  - [x] Add `<A-Del>` / `<M-Del>`
  - [x] Add `<D-Del>`
* [x] Add `<f13...f20>`
  - [x] Add `<S-{f13...f20}>`
  - [x] Add `<C-{f13...f20}>`
  - [x] Add `<C-S-{f13...f20}>`
  - [x] Add  `<A-{f13...f20}>` / `<M-{f13...f20}>`
* [x] Add keypad keys e.g. `<k0>` ... `<k9>`, `<kPlus>`, `<kMinus>`  **(Implemented as of 1.20.0)**
* [ ] Add aliases `<C-{uppercase}>` -> `<C-S-{lowercase}>` (or vice versa), `<D-{uppercase}>` -> `<D-S-{lowercase}>` (or vice versa), and `<M-{uppercase}>` -> `<M-S-{lowercase}>` (or vice versa)
* [x] Add aliases `<M-right>` (`alt+right`) -> `<l>` (`right`)  **(Implemented as of 1.19.0)**
* [x] Add aliases `<M-left>` (`alt+left`) -> `<h>` (`left`)  **(Implemented as of 1.19.0)**
* [x] Add `<D-bs>`, `<D-cr>`, `<D-del>`, `<D-down>`, `<D-home>`, `<D-left>`, `<D-pagedown>`, `<D-right>`, `<D-space>`, `<D-up>`, `<D-.>`, `<D-S-.>` so that they can be mapped from the rc file **(Implemented as of 1.19.0)**
* [x] Add `<C-home>` alias to `gg`  **(Implemented as of 1.19.0)**
* [x] Add `<C-pagedown>` alias to `gt`  **(Implemented as of 1.19.0)**
* [x] Add `ctrl+right` `<C-Right>` alias to `W`  **(Implemented as of 1.19.0)**
* [x] Add `shift+right` `<S-Right>` alias to `w`  **(Implemented as of 1.19.0)**
* [x] Add `ctrl+left` `<C-Left>` alias to `B`  **(Implemented as of 1.19.0)**
* [x] Add `shift+left` `<S-Left>` alias to `b`  **(Implemented as of 1.19.0)**
* [x] Add `<S-Down>` alias to `<C-f>`  **(Implemented as of 1.19.0)**
* [x] Add `<S-Up>` alias to `<C-b>`  **(Implemented as of 1.19.0)**

## Plugins

plugin | implemented | notes
--- | --- | ---
**Abolish** | :white_check_mark: | Currently only supports case mutation algorithms
**Indent Object** | :heavy_check_mark: |
**Commentary** | :heavy_check_mark: |
**Easy Motion** | | |
**Multiple Cursors** | :heavy_check_mark: |
**Sneak** | | |
**Surround** | :heavy_check_mark: |
**Unimpaired** | :heavy_check_mark: |
**XKeySwitch** | | |

* [x] **Naming conventions**: all plugins should start with a lowercase letter followed by lowercase letters or underscores ~and must end with a lowercase letter~, it would be expressed thus: `^[a-z]([a-z]*|[a-z_]+[a-z])$`. ~Maybe restrict plugin names to only lowercase letters i.e. `^[a-z]+$`?~
* [x] Rework multiple cursors to work closer to [terryma/vim-multiple-cursors](https://github.com/terryma/vim-multiple-cursors) [#251](https://github.com/NeoVintageous/NeoVintageous/issues/251) **(Implemented as of 1.13.0)**
* [x] **Move all non-standard commands into their own plugin modules**: some non-standard Vim commands are implemented in the Neo core. These commands should be refactored into plugin modules, for example the Commentary plugin commands and some Indent Object plugin commands are currently implemented as core commands oppose to plugin commands.
  - [x] **Sublime Text**  **(Implemented as of 1.20.0)**
    * [x] Move all ST specific commands into a "sublime" plugin e.g. `ctrl-k ctrl-b` toggles the side bar, but it's not a standard Vim command, however some commands make sense in an ST context.  **(Implemented as of 1.20.0)**
    * [x] `CTRL-P` by default should be the same as k and Up. Currently it invokes the fuzzy file finder but that should be refactored into a plugin which can be disabled, which would then default that key to this command)  **(Implemented as of 1.20.0)**

  - [x] **[*Commentary*](https://github.com/tpope/vim-commentary)** **(implemented as of 1.9.0)**

  - [x] **[Multiple Cursors](https://github.com/terryma/vim-multiple-cursors)** **(Implemented as of 1.13.0/1.18.0)**

  - [x] **[*Indent Object*](https://github.com/michaeljsmith/vim-indent-object)** #373

* [ ]  Add **vim-abolish** patterns, abbreviations, substitutions, etc. features (re #692)

* [ ]  Port **vim-sneak** #457

* [ ] Port **vim-easymotion** #276 

* [ ] Port **vim-xkbswitch** #276 or comparative plugin (for example allow to "disable Input Method when exiting Insert mode"  #374)

## Performance

* [x] [#381](https://github.com/NeoVintageous/NeoVintageous/issues/381) Movement by visual line gj and gk is laggy **(fixed as of < 2.0.0)**
* [x] [#709](https://github.com/NeoVintageous/NeoVintageous/issues/709) Improve general performance of commands 

See also https://github.com/NeoVintageous/NeoVintageous/issues?q=label%3Aperformance+

## Checklist for next major version (**2.0.0**)

* [ ] Remove deprecations
* [ ] Remove future compatibility patches
* [ ] Remove all references to "vintageous"

## Known Issues

The following are known issues that can't yet be fixed or implemented due to limitations in Sublime Text:

description | issue | sublime text issue
----------- | ----- | ------------------
**Relative line numbers** | #13 | sublimehq/sublime_text#3240
**'scrolloff' option** | #205 | sublimehq/sublime_text#3240
**Can't move cursor left and right in visual line mode** | #640 | sublimehq/sublime_text#3240
**Goto symbol within a file automatically enters visual mode** | #54 | sublimehq/sublime_text#3032
**Window status is flaky** | | sublimehq/sublime_text#627
**Spell checking commands are flaky** | | sublimehq/sublime_text#2539

See also https://github.com/NeoVintageous/NeoVintageous/issues?q=is%3Aissue+is%3Aopen+label%3Aknown-sublime-text-issue
