### ISSUE TITLE
Implement Visual block mode like Vim

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#510]
* [x] #18 Visual block do no span across empty lines
* [x] b
* [x] w
* [x] W
* [x] E
* [x] #511 Visual block to Visual line (V) doesn't work properly
* [x] #512 Visual block to Visual (v) doesn't work properly
