### ISSUE TITLE
Roadmap, part 2

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#711]
See also [part 1](#404) and [part 2](#854).

## Defaults

Defaults more closely match the Neovim defaults: [part 1](https://github.com/neovim/neovim/issues/2676) and [part 2](https://github.com/neovim/neovim/issues/6289).

* [x] Enable CTRL keys by default **(implemented in 1.23.0)**
* [x] Enable SUPER keys by default **(next major version; [2.0.0](https://github.com/NeoVintageous/NeoVintageous/milestone/19))**

## Settings

* [ ] All public settings should be prefixed with `neovintageous_` 
* [ ] All plugins should be enabled or disabled via the boolean setting `neovintageous_{plugin_name}`
* [ ] All plugins should group related settings via the prefix `neovintageous_{plugin_name}_`.
* [ ] Rework mode handling to work like Vim #385 #374 https://github.com/NeoVintageous/NeoVintageous/commit/239b3bf69b52728cb2177b3ec6297ed3168fb346
* [x] Granular key control #470 #579  **(implemented in 1.23.0)**

## Checklist for version **2.0**

* [ ] Remove deprecations
* [ ] Remove future compatibility patches
* [ ] Remove all references to "vintageous"

## Performance issues

* [x] [#709](https://github.com/NeoVintageous/NeoVintageous/issues/709) Improve general performance of commands  **(fixed as of 1.21.0)**
* [x] [#712](https://github.com/NeoVintageous/NeoVintageous/issues/712) `:help {subject}` is very slow  **(fixed as of 1.21.0)**

## Completeness

* [ ] Allow `<` and literal space " " in mappings
* [ ] Implement `[(` go to `[count]` previous unmatched '('. |exclusive| motion.
* [x] Implement `[count]` for `#`
* [x] Implement `[count]` for `*`
* [ ] Implement `[count]` for `C`
* [ ] Implement `[count]` for `D`
* [ ] Implement `[count]` for `N` after `#`
* [ ] Implement `[count]` for `N` after `*`
* [ ] Implement `[count]` for `V`
* [ ] Implement `[count]` for `a(,` `[count]a)`, and `[count]ab`
* [ ] Implement `[count]` for `a[` and `[count]a]`
* [ ] Implement `[count]` for `i(,` `[count]i)`, and `[count]ib`
* [ ] Implement `[count]` for `i[` and `[count]i]`
* [ ] Implement `[count]` for `n` after `#`
* [ ] Implement `[count]` for `n` after `*`
* [ ] Implement `[count]` for `v`
* [ ] Implement `[{` go to `[count]` previous unmatched '{'. |exclusive| motion.
* [ ] Implement `])` go to `[count]` next unmatched ')'. |exclusive| motion.
* [ ] Implement `]}` go to `[count]` next unmatched '}'. |exclusive| motion.
* [ ] Implement `g*`, `g#`, etc.
* [ ] `X` on empty line should delete line `x\n|\nx` -> `X` -> `x\n|x`
* [ ] `d$` on empty line should not ring visual bell
* [ ] `d0` on empty line should not ring visual bell
* [ ] `d^` on empty line should not ring visual bell
* [ ] `gJ`
* [ ] `gU` noop should do visual bell
* [ ] `gqip` should move cursor to last line of block
* [ ] `gu` noop should do visual bell
* [ ] `ip` and `ap`, should enter VISUAL LINE mode
* [ ] `iw`, `aW`, `iW`, `as`, `is`, etc., when in VISUAL LINE, should enter VISUAL characterwise
* [ ] Add aliases `<C-{uppercase}>` -> `<C-S-{lowercase}>` (or vice versa), `<D-{uppercase}>` -> `<D-S-{lowercase}>` (or vice versa), and `<M-{uppercase}>` -> `<M-S-{lowercase}>` (or vice versa)

## Known issues

The following are known issues that can't yet be fixed or implemented due to limitations in Sublime Text:

description | issue | sublime text issue
----------- | ----- | ------------------
~Relative line numbers~ **(fixed in 4074/1.22.0)** | #13 | sublimehq/sublime_text#3240
~'scrolloff' option~ **(implemented in 4075/1.22.0)**  | #205 | sublimehq/sublime_text/issues/2983
**Can't move cursor left and right in visual line mode** | #640 | sublimehq/sublime_text/issues/3033
**Goto symbol within a file automatically enters visual mode** | #54 | sublimehq/sublime_text#3032
**Window status is flaky** | | sublimehq/sublime_text#627
**Spell checking commands are flaky** | | sublimehq/sublime_text#2539
~Can't see cursor on search highlights~ **(fixed in 4086)** | #713 | sublimehq/sublime_text#2874
~Can't see caret~ **(fixed in 4086)** | | sublimehq/sublime_text#2695
Wrap Lines regression >=4061 | #774 | sublimehq/sublime_text#3177

## Plugins

plugin | status | notes
--- | --- | ---
**Abolish** | :white_check_mark: |
**Commentary** | :white_check_mark: | 
**Easy Motion** |  |
**Highlighted Yank** | :heavy_check_mark: |
**Indent Object** | :heavy_check_mark: |
**Multiple Cursors** | :heavy_check_mark: |
**Sneak** | :white_check_mark: | [disabled by default](https://github.com/NeoVintageous/NeoVintageous/issues/731)
**Surround** | :white_check_mark: | |
**Targets** | :white_check_mark: | |
**Unimpaired** | :white_check_mark: | | 
**XKeySwitch** | |

### Abolish

Abolish is a port of the popular [vim-abolish](https://github.com/tpope/vim-abolish).

```
Status | Key Sequence             | Description
-------|--------------------------|----------------------------------------------
[x]    | cr{algorithm}            | Case mutating algorithms.
[ ]    | :Abolish                 | Search and substitute.
[ ]    | :Subvert                 | More concise syntax for search and substitute.
```

### Commentary

Commentary is a port of the popular [vim-commentary](https://github.com/tpope/vim-commentary).

```
Status | Key Sequence             | Description
-------|--------------------------|----------------------------------------------
[x]    | gc{motion}               | Comment or uncomment lines that {motion} moves over.
[x]    | gc                       | Comment or uncomment [count] lines.
[x]    | {Visual}gc               | Comment or uncomment the highlighted lines.
[x]    | gc                       | Text object for a comment (operator pending mode only).
[ ]    | gcgc or gcu              | Uncomment the current and adjacent commented lines.
```

### Easy Motion

* [ ] Port **vim-easymotion** #276 

### Highlighted Yank

Inspired by [vim-highlightedyank](https://github.com/machakann/vim-highlightedyank).

### Indent Object

Indent Object is a port of the popular [vim-indent-object](https://github.com/michaeljsmith/vim-indent-object).

```
Status | Key Sequence             | Description
-------|--------------------------|----------------------------------------------
[x]    | <count>ai                | (A)n (I)ndentation level and line above.
[x]    | <count>ii                | (I)nner (I)ndentation level (no line above).
[x]    | <count>aI                | (A)n (I)ndentation level and lines above/below.
[x]    | <count>iI                | (I)nner (I)ndentation level (no lines above/below).
```

### Multiple Cursors

Inspired by [vim-multiple-cursors](https://github.com/terryma/vim-multiple-cursors).

### Sneak 

Sneak is a port of the popular [vim-sneak](https://github.com/justinmk/vim-sneak).

```
NORMAL-MODE

Status | Key Sequence             | Description
-------|--------------------------|----------------------------------------------
[x]    | s{char}{char}            | Go to the next occurrence of {char}{char}
[x]    | S{char}{char}            | Go to the previous occurrence of {char}{char}
[x]    | s{char}<Enter>           | Go to the next occurrence of {char}
[x]    | S{char}<Enter>           | Go to the previous occurrence of {char}
[x]    | s<Enter>                 | Repeat the last Sneak.
[x]    | S<Enter>                 | Repeat the last Sneak, in reverse direction.
[x]    | ;                        | Go to the [count]th next match
[x]    | , or \                   | Go to the [count]th previous match
[ ]    | s                        | Go to the [count]th next match (see NOTE)
[ ]    | S                        | Go to the [count]th previous match (see NOTE)
[ ]    | [count]s{char}{char}     | Invoke |sneak-vertical-scope|
[ ]    | [count]S{char}{char}     | Invoke backwards |sneak-vertical-scope|
[x]    | {operator}z{char}{char}  | Perform {operator} from the cursor to the next
                                  | occurrence of {char}{char}
[x]    | {operator}Z{char}{char}  | Perform {operator} from the cursor to the
                                  | previous occurrence of {char}{char}

NOTE: s and S go to the next/previous match immediately after invoking Sneak, if
|sneak-clever-s| is enabled.

VISUAL-MODE

Status | Key Sequence             | Description
-------|--------------------------|----------------------------------------------
[x]    | s{char}{char}            | Go to the next occurrence of {char}{char}
[x]    | Z{char}{char}            | Go to the previous occurrence of {char}{char}
[x]    | s{char}<Enter>           | Go to the next occurrence of {char}
[x]    | Z{char}<Enter>           | Go to the previous occurrence of {char}
[x]    | s<Enter>                 | Repeat the last Sneak.
[x]    | Z<Enter>                 | Repeat the last Sneak, in reverse direction.
[x]    | ;                        | Go to the [count]th next match
[x]    | , or \                   | Go to the [count]th previous match
[ ]    | s                        | Go to the [count]th next match (NOTE above)
[ ]    | S                        | Go to the [count]th previous match (NOTE above)

NOTE: Z goes backwards in visual-mode, because S is taken by the |surround|
plugin).

LABEL-MODE

Status | Key Sequence             | Description
-------|--------------------------|----------------------------------------------
[ ]    | <Space> or <Esc>         | Exit |sneak-label-mode| where the cursor is.
[ ]    | <Tab>                    | Label the next set of matches.
[ ]    | <BS> or <S-Tab>          | Label the previous set of matches.
```

### Surround

Surround is a port of the popular [vim-surround](https://github.com/tpope/vim-surround).

```
Status | Key Sequence             | Description
-------|--------------------------|----------------------------------------------
[x]    | cs                       | Change surroundings.
[x]    | ds                       | Delete surroundings.
[x]    | ys                       | Yank and change surroundings.
[x]    | yss                      | Operates on current line, ignoring whitespace.
[x]    | {Visual}S                | With an argument wraps the selection.
[ ]    | cS                       | Change surroundings and put on own line.
[ ]    | yS                       | Yank and change surroundings and put on own line.
```

### Targets

Targets.vim is a Vim plugin that adds various text objects to give you more targets to operate on. 

https://github.com/wellle/targets.vim

### Unimpaired 

Unimpaired is a port of the popular [vim-unimpaired](https://github.com/tpope/vim-unimpaired).

### xkb Switch

* [ ] Port **vim-xkbswitch** #276 or comparative plugin (for example allow to "disable Input Method when exiting Insert mode"  #374)

**Comment by gerardroche** [comment]
See https://github.com/NeoVintageous/NeoVintageous/issues/854
