### ISSUE TITLE
Roadmap, part 3

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#854]
See also [Part 1](#404) and [Part 2](#711)

* [x] #924 (**Implemented in 1.32.0**)
* [ ] https://github.com/NeoVintageous/NeoVintageous/discussions/927
* [ ] All private settings should have a consistent prefix
* [ ] Rework mode handling to work like Vim #385 #374 https://github.com/NeoVintageous/NeoVintageous/commit/239b3bf69b52728cb2177b3ec6297ed3168fb346
* [ ] Remove deprecations

## Completeness

This is list of mainly small edge cases or low priority enhancements. They are listed here instead of having dedicated opened issues.

* [ ] Allow `<` and literal space " " in mappings
* [ ] Implement `[(` go to `[count]` previous unmatched '('. |exclusive| motion.
* [x] #860 (**Implemented in 1.29.0**)
* [x] #861 (**Implemented in 1.29.0**)
* [x] #858 (**Implemented in 1.29.0**)
* [x] Implement `[count]` for `N` after `#` (**Implemented in 1.27.0**)
* [x] Implement `[count]` for `N` after `*` (**Implemented in 1.27.0**)
* [x] #904  (**Implemented in 1.31.0**)
* [ ] Implement `[count]` for `a(,` `[count]a)`, and `[count]ab`
* [ ] Implement `[count]` for `a[` and `[count]a]`
* [ ] Implement `[count]` for `i(,` `[count]i)`, and `[count]ib`
* [ ] Implement `[count]` for `i[` and `[count]i]`
* [x] Implement `[count]` for `n` after `#` (**Implemented in 1.27.0**)
* [x] Implement `[count]` for `n` after `*` (**Implemented in 1.27.0**)
* [ ] Implement `[count]` for `v`
* [ ] Implement `[{` go to `[count]` previous unmatched '{'. |exclusive| motion.
* [ ] Implement `])` go to `[count]` next unmatched ')'. |exclusive| motion.
* [ ] Implement `]}` go to `[count]` next unmatched '}'. |exclusive| motion.
* [ ] Implement `g*`, `g#`, etc.
* [x] ~`X` on empty line should delete line `x\n|\nx` -> `X` -> `x\n|x`~
* [x] ~`d$` on empty line should not ring visual bell~
* [x] ~`d0` on empty line should not ring visual bell~
* [x] ~`d^` on empty line should not ring visual bell~
* [ ] `gJ`
* [x] ~`gU` noop should do visual bell~
* [ ] `gqip` should move cursor to last line of block
* [x] ~`gu` noop should do visual bell~
* [ ] `ip` and `ap`, should enter VISUAL LINE mode
* [ ] `iw`, `aW`, `iW`, `as`, `is`, etc., when in VISUAL LINE, should enter VISUAL characterwise
* [ ] Add alias `<C-S-{char}>` => `<C-{uppercase}>`
* [ ] Add alias `<D-S-{char}>` => `<D-{uppercase}>`
* [ ] Add alias `<M-S-{char}>` => `<M-{uppercase}>`

## Plugin status

See [roadmap, plugins](https://github.com/NeoVintageous/NeoVintageous/issues/855) for a complete status of current plugins.

## Known issues

description | issue | sublime text issue
----------- | ----- | ------------------
Can't move cursor left and right in visual line mode | #640 | sublimehq/sublime_text/issues/3033
Goto symbol within a file automatically enters visual mode | #54 | sublimehq/sublime_text#3032
Window status is flaky | | sublimehq/sublime_text#627
Spell checking commands are flaky | | sublimehq/sublime_text#2539
Wrap Lines regression >=4061 | #774 | sublimehq/sublime_text#3177
Symbol jumping does not select text |  #753 | sublimehq/sublime_text#3032
Interactive command line prompts | #157 |

**Comment by gerardroche** [comment]
Close in preference for roadmap here: https://github.com/NeoVintageous/NeoVintageous/blob/master/ROADMAP.md
