### ISSUE TITLE
Roadmap, plugins

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#855]
Plugin | Status | Notes
------ | ------ | -----
Abolish | :heavy_check_mark: |
Commentary | :heavy_check_mark: | 
Highlighted Yank | :heavy_check_mark: |
Indent Object | :heavy_check_mark: |
Multiple Cursors | :heavy_check_mark: |
Sneak | :heavy_check_mark: | [disabled by default](https://github.com/NeoVintageous/NeoVintageous/issues/731)
Surround | :heavy_check_mark: | |
Targets | :heavy_check_mark: | |
Unimpaired | :heavy_check_mark: | | 

Suggestions for future implemenation

Plugin | Original Vim Plugin | Notes
------ | ------------------- | -----
Hop | [hop.nvim](https://github.com/phaazon/hop.nvim) | Re https://github.com/NeoVintageous/NeoVintageous/issues/808
WhichKey | [vim-which-key](https://github.com/liuchengxu/vim-which-key) | Re https://github.com/NeoVintageous/NeoVintageous/issues/758
SurroundAny | | Re https://github.com/NeoVintageous/NeoVintageous/issues/743
YankStackAndRing | | Re https://github.com/NeoVintageous/NeoVintageous/issues/337
XkbSwitch | [vim-xkbswitch](https://github.com/lyokha/vim-xkbswitch) | Re https://github.com/NeoVintageous/NeoVintageous/issues/276
EasyMotion | [vim-easymotion](https://github.com/easymotion/vim-easymotion) | Re https://github.com/NeoVintageous/NeoVintageous/issues/276

## Current plugin status

**Abolish**

A port of [vim-abolish](https://github.com/tpope/vim-abolish).

- [x] `cr{algorithm}` - Case mutating algorithms.
- [ ] `:Abolish` - Search and substitute.
- [ ] `:Subvert` - More concise syntax for search and substitute.

**Commentary**

A port of [vim-commentary](https://github.com/tpope/vim-commentary).

- [x] `gc{motion}` - Comment or uncomment lines that {motion} moves over.
- [x] `gc` - Comment or uncomment [count] lines.
- [x] `{Visual}gc` - Comment or uncomment the highlighted lines.
- [x] `gc` - Text object for a comment (operator pending mode only).
- [ ] `gcgc` or gcu - Uncomment the current and adjacent commented lines.

**Highlighted Yank**

Inspired by [vim-highlightedyank](https://github.com/machakann/vim-highlightedyank). See `help nv` for details.

**Indent Object**

A port of [vim-indent-object](https://github.com/michaeljsmith/vim-indent-object).

- [x] `<count>ai` - (A)n (I)ndentation level and line above.
- [x] `<count>ii` - (I)nner (I)ndentation level (no line above).
- [x] `<count>aI` - (A)n (I)ndentation level and lines above/below.
- [x] `<count>iI` - (I)nner (I)ndentation level (no lines above/below).

**Multiple Cursors**

Inspired by [vim-multiple-cursors](https://github.com/terryma/vim-multiple-cursors). See `help nv` for details.

**Sneak**

A port of [vim-sneak](https://github.com/justinmk/vim-sneak).

NORMAL-MODE

- [x] `s{char}{char}` - Go to the next occurrence of `{char}{char}`
- [x] `S{char}{char}` - Go to the previous occurrence of `{char}{char}`
- [x] `s{char}<Enter>` - Go to the next occurrence of `{char}`
- [x] `S{char}<Enter>` - Go to the previous occurrence of `{char}`
- [x] `s<Enter>` - Repeat the last Sneak.
- [x] `S<Enter>` - Repeat the last Sneak, in reverse direction.
- [x] `;` - Go to the `[count]`th next match
- [x] `,` or \ - Go to the `[count]`th previous match
- [ ] `s` - Go to the `[count]`th next match (see NOTE)
- [ ] `S` - Go to the `[count]`th previous match (see NOTE)
- [ ] `[count]s{char}{char}` - Invoke sneak-vertical-scope
- [ ] `[count]S{char}{char}` - Invoke backwards sneak-vertical-scope
- [x] `{operator}z{char}{char}` - Perform `{operator}` from the cursor to the next occurrence of `{char}{char}`
- [x] `{operator}Z{char}{char}` - Perform `{operator}` from the cursor to the previous occurrence of `{char}{char}`

VISUAL-MODE

- [x] `s{char}{char}` - Go to the next occurrence of `{char}{char}`
- [x] `Z{char}{char}` - Go to the previous occurrence of `{char}{char}`
- [x] `s{char}<Enter>` - Go to the next occurrence of `{char}`
- [x] `Z{char}<Enter>` - Go to the previous occurrence of `{char}`
- [x] `s<Enter>` - Repeat the last Sneak.
- [x] `Z<Enter>` - Repeat the last Sneak, in reverse direction.
- [x] `;` - Go to the [count]th next match
- [x] `,` or \ - Go to the [count]th previous match
- [ ] `s` - Go to the [count]th next match (NOTE above)
- [ ] `S` - Go to the [count]th previous match (NOTE above)

LABEL-MODE

- [ ] `<Space>` or <Esc> - Exit |sneak-label-mode| where the cursor is.
- [ ] `<Tab>` - Label the next set of matches.
- [ ] `<BS>` or <S-Tab> - Label the previous set of matches.

**Surround**

A port of [vim-surround](https://github.com/tpope/vim-surround).

- [x] `cs` - Change surroundings.
- [x] `ds` - Delete surroundings.
- [x] `ys` - Yank and change surroundings.
- [x] `yss` - Operates on current line, ignoring whitespace.
- [x] `{Visual}S` - With an argument wraps the selection.
- [ ] `cS` - Change surroundings and put on own line.
- [ ] `yS` - Yank and change surroundings and put on own line.

**Targets**

Inspired by [targets.vim](https://github.com/wellle/targets.vim).

**Unimpaired**

A port of [vim-unimpaired](https://github.com/tpope/vim-unimpaired).

- [ ] `[a` - `:previous`
- [ ] `]a` - `:next`
- [ ] `[A` - `:first`
- [ ] `]A` - `:last`
- [x] `[b` - `:bprevious`
- [x] `]b` - `:bnext`
- [x] `[B` - `:bfirst`
- [x] `]B` - `:blast`
- [x] `[l` - `:lprevious`
- [x] `]l` - `:lnext`
- [ ] `[L` - `:lfirst`
- [ ] `]L` - `:llast`
- [ ] `[<C-L>` - `:lpfile`
- [ ] `]<C-L>` - `:lnfile`
- [ ] `[q` - `:cprevious`
- [ ] `]q` - `:cnext`
- [ ] `[Q` - `:cfirst`
- [ ] `]Q` - `:clast`
- [ ] `[<C-Q>` - `:cpfile` (Note that `<C-Q>` only works in a terminal if you disable
- [ ] `]<C-Q>` - `:cnfile` flow control: stty -ixon)
- [x] `[t` - `:tprevious`
- [x] `]t` - `:tnext`
- [x] `[T` - `:tfirst`
- [x] `]T` - `:tlast`
- [ ] `[<C-T>` - `:ptprevious`
- [ ] `]<C-T>` - `:ptnext`
- [ ] `[f` - Go to the file preceding the current one alphabetically in the current file's directory.  In the quickfix window, equivalent to `:colder`.
- [ ] `]f` - Go to the file succeeding the current one alphabetically in the current file's directory.  In the quickfix window, equivalent to `:cnewer`.
- [x] `[n` - Go to the previous SCM conflict marker or diff/patch hunk.  Try `d[n` inside a conflict.
- [x] `]n` - Go to the next SCM conflict marker or diff/patch hunk.
- [x] `[<Space>` - Add `[count]` blank lines above the cursor.
- [x] `]<Space>` - Add `[count]` blank lines below the cursor.
- [x] `[e` - Exchange the current line with `[count]` lines above it.
- [x] `]e` - Exchange the current line with `[count]` lines below it.
- [ ] `>p` - Paste after linewise, increasing indent.
- [ ] `>P` - Paste before linewise, increasing indent.
- [ ] `<p` - Paste after linewise, decreasing indent.
- [ ] `<P` - Paste before linewise, decreasing indent.
- [ ] `=p` - Paste after linewise, reindenting.
- [ ] `=P` - Paste before linewise, reindenting.

On / Off / Toggle / Option

- [ ] `[ob` / `]ob` / `yob` / `'background'` (dark is off, light is on)
- [x] `[oc` / `]oc` / `yoc` / `'cursorline'`
- [ ] `[od` / `]od` / `yod` / `'diff'` (actually `:diffthis` / `:diffoff`)
- [x] `[oh` / `]oh` / `yoh` / `'hlsearch'`
- [x] `[oi` / `]oi` / `yoi` / `'ignorecase'`
- [x] `[ol` / `]ol` / `yol` / `'list'`
- [x] `[on` / `]on` / `yon` / `'number'`
- [x] `[or` / `]or` / `yor` / `'relativenumber'`
- [x] `[os` / `]os` / `yos` / `'spell'`
- [ ] `[ot` / `]ot` / `yot` / `'colorcolumn'` ("+1" or last used value)
- [ ] `[ou` / `]ou` / `you` / `'cursorcolumn'`
- [ ] `[ov` / `]ov` / `yov` / `'virtualedit'`
- [x] `[ow` / `]ow` / `yow` / `'wrap'`
- [ ] `[ox` / `]ox` / `yox` / `'cursorline'` `'cursorcolumn'` (x as in crosshairs)

**Comment by gerardroche** [comment]
Close in preference for roadmap here: https://github.com/NeoVintageous/NeoVintageous/blob/master/ROADMAP.md
